language: generic

sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

script:
  - docker build -t $DOCKER_USERNAME/inspirobot .
  - docker run -d $DOCKER_USERNAME/inspirobot
  - docker ps -a

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_USERNAME/inspirobot;
    fi